---
- name: Installing Kafka
  hosts: all
  become: true
  tasks:
    - name: update the package
      ansible.builtin.apt:
        update_cache: true
        name: default-jdk 
        state: present
    
    - name: download the khafka tar files
      ansible.builtin.get_url:
        url: https://downloads.apache.org/kafka/3.3.1/kafka_2.13-3.3.1.tgz
        dest: /home/krish

    - name: Creating a destination folder for kafka files
      ansible.builtin.file:
        path: /usr/local/kafka 
        state: directory
    
    - name: Unarchiving the kafka files
      ansible.builtin.unarchive:
        src: /home/krish/kafka_2.13-3.3.1.tgz
        dest: /usr/local/kafka
        remote_src: yes

    - name: Adding Zookeper service file to systemd
      ansible.builtin.template:
        src: /variable/zookeper.service.j2
        dest: /etc/systemd/system/zookeeper.service 
          
    - name: Adding kafka service file to systemd
      ansible.builtin.template:
        src: /variable/kafka.service.j2
        dest: /etc/systemd/system/kafka.service  

    - name: Restarting the systemd files for services
      ansible.builtin.systemd:
        daemon_reload: yes
        name: "{{item}}"
        state: started
      loop: "{{service}}"  

      